---
title: Glossaar architecture
---

flowchart TB
    Browser --> DNS
	DNS --> Server
    Server --> DockerHost
	NginxContainer -->|/api| BeContainer
	NginxContainer -->|/| FeContainer

	BeContainer --> DbContainer

	subgraph DockerHost["Docker Host"]
		direction TB

		subgraph NginxContainer["Nginx container"]
			Nginx
		end

		subgraph BeContainer["BE container"]
			Be[
				- Java Spring boot
				- JPA
				- Liquibase
			]
		end

		subgraph FeContainer["FE container (nginx)"]
			Fe[
				- SvelteKit static
				- shadcn-svelte
			]
		end

		subgraph DbContainer["DB container"]
			DB[(PSQL)]
		end
	end

%% TODO: add multiple BE containers
%% TODO: add monitoring
%% TODO: add background jobs
