services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - "8080:8080"
    command: mvn -q -DskipTests spring-boot:run
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src
          initial_sync: true
        - action: sync+restart
          path: ./backend/pom.xml
          target: /app/pom.xml
          initial_sync: true
        - action: rebuild
          path: ./backend/Dockerfile.dev

  frontend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -lc "npm ci && npm run dev"

  # Debug DB state a bit easier than via the postgres cli. You can use these credentials below but you'll still need to set up the DB connection itself inside pgadmin.
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ee@ee.ee
  #     PGADMIN_DEFAULT_PASSWORD: ee@ee.ee
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  pgdata:
  m2:
  frontend_node_modules:
  pgadmin: