services:
  db:
    image: postgres:18-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    working_dir: /app
    volumes:
      - m2:/root/.m2
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - "8080:8080"
    command: mvn -q -DskipTests spring-boot:run
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src
          initial_sync: true
        - action: sync+restart
          path: ./backend/pom.xml
          target: /app/pom.xml
          initial_sync: true
        - action: rebuild
          path: ./backend/Dockerfile.dev

  frontend:
    image: node:lts-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DOCKER_ENV: "true"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -lc "npm ci && npm run dev"

volumes:
  pgdata:
  m2:
  frontend_node_modules: