

services:
  frontend:
    image: ghcr.io/taltech-vanemarendajaks/team-01-glossaar-frontend:latest
    # No ports exposed, as nginx will proxy requests to its default port 80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

# BE:  TODO: setup
# DB:  TODO: setup
