
# !!! presumes creating the network with `docker network create shared-proxy` beforehand (necessary for nginx to be able to communicate with borsibaar containers) !!!
networks:
  shared-proxy:
    external: true

services:
  frontend:
    # No ports exposed, as nginx will proxy requests to its default port 80
    image: ghcr.io/taltech-vanemarendajaks/team-01-glossaar/frontend:latest
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped

  backend:
    # No ports exposed, as nginx will proxy requests to its default port 8080
    image: ghcr.io/taltech-vanemarendajaks/team-01-glossaar/backend:latest
    restart: unless-stopped

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # using the certs we have on the server
    restart: unless-stopped
    networks:
      - default
      - shared-proxy

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: glossaar_dev
      POSTGRES_USER: glossaar
      POSTGRES_PASSWORD: glossaar_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: