CREATE TABLE user_word_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    word_id BIGINT NOT NULL,
    quiz_score INTEGER NOT NULL,
    CONSTRAINT uk_user_word_score UNIQUE (user_id, word_id),
    CONSTRAINT fk_user_word_scores_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_word_scores_word FOREIGN KEY (word_id) REFERENCES words(id)
);
