CREATE TABLE eki_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    word_normalized VARCHAR(255) NOT NULL,
    lang VARCHAR(16) NOT NULL,
    homonym_nr INT NOT NULL,
    explanation VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE eki_words
    ADD CONSTRAINT uk_eki_words_word_lang_group_explanation
    UNIQUE (word_normalized, lang, homonym_nr, explanation);

CREATE INDEX idx_eki_words_word_lang
    ON eki_words (word_normalized, lang);
