# Liquibase handles db schema. If schema is changed, a new migration should be created.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# datasource should be changed locally if you are not using docker, but that change should not be committed.
spring.datasource.url=jdbc:postgresql://localhost:5432/glossaar_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Set log level here
# logging.level.org.springframework=TRACE

# Used for redirecting user back after logged in via auth provider
app.post-login-landing-url=http://localhost:5173/