spring.application.name=backend

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Set global prefix for all endpoints. Path versioning can be done here or more granularly on a controller level.
server.servlet.context-path=/api

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml