# HTTP to HTTPS redirect for borsibaar.href.ee
server {
    listen 80;
    listen [::]:80;

    server_name borsibaar.href.ee www.borsibaar.href.ee;

    if ($host = www.borsibaar.href.ee) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = borsibaar.href.ee) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    return 404; # managed by Certbot
}

# HTTPS server block for borsibaar.href.ee
server {
    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/borsibaar.href.ee/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/borsibaar.href.ee/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name borsibaar.href.ee www.borsibaar.href.ee;

    location / {
        # TODO: serve static UI files
        # try_files $uri $uri/ =404;
        add_header Content-Type text/plain;
        return 200 'borsibaar UI';
    }

    location /api {
        # TODO: proxy to backend container
        # proxy_pass localhost:port
        add_header Content-Type text/plain;
        return 200 'borsibaar api';
        # proxy_pass http://localhost:8000/api;
        # proxy_http_version 1.1;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
    }
}
