server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/borsibaar.href.ee/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/borsibaar.href.ee/privkey.pem;

    return 444;
}
