upstream backend {
    ip_hash; # workaround for oauth issues (probably related to JSESSIONID cookie)

    server backend:8080;
    server backend-1:8080;
    server backend-2:8080;
}

# HTTP to HTTPS redirect for glossaar.href.ee
server {
    listen 80;

    server_name glossaar.href.ee www.glossaar.href.ee;

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server block for glossaar.href.ee
server {
    listen 443 ssl; # managed by Certbot

    # TODO: create new certs for glossaar.href.ee instead of using borsibaar.href.ee
    ssl_certificate /etc/letsencrypt/live/borsibaar.href.ee/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/borsibaar.href.ee/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name glossaar.href.ee www.glossaar.href.ee;

    location / {
        # Necessary for connection not dying when proxying to frontend nginx container.
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://frontend:80; # frontend container
    }


    location /api/ {
        # Enable directing UI running on localhost to the backend running in the server.
        # In a real world web app, the requests should be limited to known origins and methods, but for development purposes we allow all.
        # Spring application will also validate the requests
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "*" always;
        add_header Access-Control-Allow-Headers "*" always;
        add_header Access-Control-Max-Age 86400 always;

        # Preflight
        if ($request_method = OPTIONS) {
            return 204;
        }

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://backend; # backend container, preserve full path
    }

    location /login/oauth2/code/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://backend; # backend container, preserve full path
    }

    location /logout {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://backend;
    }

    location /login/google {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/login/google$ /oauth2/authorization/google break;
        proxy_pass http://backend;
    }

    location /login/github {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/login/github$ /oauth2/authorization/github break;
        proxy_pass http://backend;
    }
}
