# HTTP to HTTPS redirect for glossaar.href.ee
server {
    listen 80;
    listen [::]:80;

    server_name glossaar.href.ee www.glossaar.href.ee;

    if ($host = www.glossaar.href.ee) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = glossaar.href.ee) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    return 404; # managed by Certbot
}

# HTTPS server block for glossaar.href.ee
server {
    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/borsibaar.href.ee/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/borsibaar.href.ee/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name glossaar.href.ee www.glossaar.href.ee;

    root /var/www/glossaar;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # TODO: proxy to backend container
        # proxy_pass localhost:port
        add_header Content-Type text/plain;
        return 200 'glossaar api';
    }
}
