name: PR Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven


      - name: Build and Run Backend Tests
        working-directory: backend
        run: mvn clean test