name: Build and publish Docker image

# TODO: if main branch gets a merge, check whether frontend and backend have changes, and only build and deploy the one that has changes

on:
  workflow_dispatch:
    inputs:
      component:
        description: Component to build and deploy
        required: true
        options:
          - frontend
          # - backend

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.component }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ inputs.component }}:latest
            ghcr.io/${{ github.repository }}/${{ inputs.component }}:${{ github.sha }}