name: Build and publish Docker image

on:
  workflow_dispatch:
    inputs:
      component:
        description: Application component to build and deploy to GHCR
        type: choice
        required: true
        options:
          - frontend
          - backend

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.component }}
          push: true
          tags: |
            ghcr.io/taltech-vanemarendajaks/team-01-glossaar/${{ inputs.component }}:latest
            ghcr.io/taltech-vanemarendajaks/team-01-glossaar/${{ inputs.component }}:${{ github.sha }}

# TODO: Add a step to trigger deployment on the server after pushing the image, e.g., via SSH or some webhook solution
