name: Publish image to GHCR

on:
  workflow_dispatch:
    inputs:
      component:
        description: Application component to build and publish to GHCR
        type: choice
        required: true
        options:
          - frontend
          - backend

permissions:
  contents: read
  packages: write

jobs:
  run-fe-tests:
    if: inputs.component == 'frontend'
    uses: ./.github/workflows/frontend-tests.yml

  run-be-tests:
    if: inputs.component == 'backend'
    uses: ./.github/workflows/backend-tests.yml

  build-and-publish-to-ghcr:
    needs: [run-fe-tests, run-be-tests]
    if: |
      always() &&
      (needs.run-fe-tests.result == 'success' || needs.run-fe-tests.result == 'skipped') &&
      (needs.run-be-tests.result == 'success' || needs.run-be-tests.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.component }}
          push: true
          tags: |
            ghcr.io/taltech-vanemarendajaks/team-01-glossaar/${{ inputs.component }}:latest
            ghcr.io/taltech-vanemarendajaks/team-01-glossaar/${{ inputs.component }}:${{ github.sha }}

  deploy-to-server:
    needs: build-and-publish-to-ghcr
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      component: ${{ inputs.component }}
