name: SonarCube static analysis

on:
  workflow_dispatch:
  pull_request:
    paths:
      - backend/**
      - frontend/**

jobs:
  backend-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.BACKEND_SONAR_TOKEN }}
        run: |
          cd ./backend
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=glossaar_backend

  frontend-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: SonarQube frontend scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          projectBaseDir: ./frontend
          args: >
            -Dsonar.organization=glossaar
            -Dsonar.projectName=frontend
            -Dsonar.projectKey=glossaar_frontend
        env:
          SONAR_TOKEN: ${{ secrets.FRONTEND_SONAR_TOKEN }}